openapi: 3.0.0
info:
  title: SaaS Starter API Documentation
  version: 1.0.0
  description: |
    API specification for the SaaS Starter project.
    This document is designed to be machine-readable and AI-friendly.

tags:
  - name: authentication
    description: Authentication endpoints and operations
  - name: user
    description: User management operations
  - name: dashboard
    description: Dashboard-related operations

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string

paths:
  /api/auth/[...nextauth]:
    post:
      tags: [authentication]
      summary: NextAuth.js authentication endpoint
      description: Handles all authentication flows (credentials, OAuth, etc.)
      responses:
        200:
          description: Authentication successful
        401:
          description: Authentication failed

  /api/user/profile:
    get:
      tags: [user]
      security:
        - BearerAuth: []
      summary: Get user profile
      responses:
        200:
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

# AI-Specific Metadata
x-file-fingerprints:
  - pattern: "export const authConfig"
    file: src/lib/auth/auth.config.ts
  - pattern: "export type AuthUser"
    file: src/types/auth.types.ts

x-related-docs:
  - auth-flows.md
  - error-handling-reference.md

x-version-compatibility:
  nextjs: 14.x
  node: ">=18.17.0"
  openapi: 3.0.0

x-maintenance-rules:
  - Update version number when adding/modifying endpoints
  - Regenerate API types after schema changes
  - Verify security schemes when modifying auth flows
  - Keep response examples up to date

x-common-errors:
  - title: Missing Authorization Header
    description: Ensure Bearer token is included in protected endpoints
    example: |
      # ❌ Incorrect
      fetch('/api/user/profile')
      
      # ✅ Correct
      fetch('/api/user/profile', {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      })

  - title: Invalid Route Handler
    description: Ensure API routes follow Next.js 13+ conventions
    example: |
      # ❌ Incorrect
      export default function handler(req, res) {}
      
      # ✅ Correct
      export async function GET() {}
      export async function POST() {}